### ISSUE TITLE
Research (and maybe add) possibly missing limits and probes

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-tasks#27]
I did a `kubectl --all-namespaces describe deploy` to find deployments that don't have resource limits set, or liveness or readiness probes set.

There may be a good reasons why a probe might be missing, I don't know. This task is about researching if this is the case or not, and if it's missing, implement it.

For instance, for argocd-dex-server, the Helm chart we use supports both liveness and readiness probies (https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L281), but we are using only liveness probes for some reason.

The following deployments are missing one or more of these things:

Deployment | What is missing
argocd-dex-server |                                              probes
argocd-redis |                                                   probes
aws-load-balancer-controller |                                   probes
cluster-autoscaler-aws-cluster-autoscaler |                      probes
coredns |                                                        resources
ebs-csi-controller |                                             probes
external-dns |                                                   resources, probes
external-secrets-kubernetes-external-secrets |                   probes     
kube-prometheus-stack-grafana |                                  resources
kube-prometheus-stack-kube-state-metrics |                       resources
kube-prometheus-stack-operator |                                 probes   

In above table, when I wrote "probes", this can mean liveness OR readiness probes, or both.

** Motivation **

For Kubernetes and Fargate to properly schedule hardware and organize pods, we need to help them by defining ResourceQuota's and Probes. All services should have ResourceQuota's and Probes.

** Task **
1. Go through the list above and verify wether they have the required probes (readiness probe and liveness probe) and limits (resourceQuota for memory and CPU). Depending on the resource type, this can be done with `kubectl -n <relevant namespace> get <resource type> -o yaml`. Relevant namespace for ArgoCD related services is `argocd`. Relevant namespace for Prometheus related services is `monitoring`. The rest are located in `kube-system`.
2. Create a task to add probes and / or limits to the services that are missing them. 

*** Adding probes / limits ***

N.B.: This is not part of the GoodFirstTask

2. Identify where in the okctl code we define probes for services missing probes. For example, for ArgoCD its in the [values.yaml](https://github.com/oslokommune/okctl/blob/master/pkg/helm/charts/argocd/values-template.yaml). (N.B.: the chart we use to install the service might not support probes)
3. Try to define reasonable probes and / or limits. Here you should look up what is default in Kubernetes. Maybe try to cross reference with other installations found by searching the net.

**Comment by yngvark** [comment]
This is an old task from our Trello which we will not solve due to chaning to new Golden Path.
