### ISSUE TITLE
Oppdater artikkel på Labs

### ISSUE THREAD

**Issue by Kielo87** [oslokommune/kjoremiljo-admin-tasks#33]
Artikkelen om Kjøremiljø på labs må oppdateres med 
- [x] Nytt team bilde
- [x] Bildetekst
- [x] Nytt url for prosjektstyring

**Comment by leiacf** [comment]
Ny url må vente på at #35 blir klar

**Comment by leiacf** [comment]
#35 er klar, så da kan vi slenge ut ny url i alle fall :)

**Comment by Kielo87** [comment]
Artikkelen er oppdatert
