### ISSUE TITLE
Figure out if it's possible to automatically close a github issue when a project card is moved to the completed column

### ISSUE THREAD

**Issue by leiacf** [oslokommune/kjoremiljo-admin-tasks#34]
While closing an issue moves it to "completed" through workflows, the oposite is not true. This means that when we close the issues in our planning, we have to do it from "issues", not from the project board overview :( 

https://github.com/dear-github/dear-github/issues/284 discusses the problem, and has some workarounds that we might explore to see if we can automate it somehow

**Comment by yngvark** [comment]
Duplikat av #41
